config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "homepage#show"

  resources :video_calls, only: [:new, :create, :show], param: :uuid do
    member do
      post :join
      post :invite
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/video_call.rb
class VideoCall < ApplicationRecord
  def to_param
    uuid
  end

  validates_presence_of :name, :uuid, :session_id, :application_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def show
  end
end

app/controllers/video_calls_controller.rb
class VideoCallsController < ApplicationController
  def new
    @video_call = VideoCall.new
  end

  def create
    @video_call = VideoCall.new(
      application_id: ENV['VONAGE_APPLICATION_ID'],
      uuid: SecureRandom.uuid,
      **video_call_params
    )

    begin
      vonage_video_session = Vonage.video.create_session
      @video_call.session_id = vonage_video_session.session_id

      if @video_call.save
        redirect_to @video_call
      else
        flash[:alert] = "Unable to create video call."
        render :new, status: :unprocessable_entity 
      end
    rescue => error
      logger.info(error)
      flash[:alert] = "Unable to create video call."
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @video_call = VideoCall.find_by!(uuid: params[:uuid])
    @token = Vonage.video.generate_client_token(session_id: @video_call.session_id) if session[:participant_name].present?
  end

  def join
    @video_call = VideoCall.find_by(uuid: params[:uuid])
    session[:participant_name] = params[:participant_name]

    redirect_to @video_call
  end

  def invite
    site_url = Rails.env.local? ? ENV['SITE_URL'] : ENV['RENDER_EXTERNAL_URL']
    message_text = "Hi #{params[:participant_name]}. Join my video call at #{site_url}/video_calls/#{params[:uuid]}"
    message = Vonage.messaging.sms(message: message_text)
    Vonage.messaging.send(
      from: ENV['VONAGE_NUMBER'],
      to: params[:participant_phone_number],
      **message
    )

    head :ok
  end

  private

  def video_call_params
    params.require(:video_call).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/homepage/show.html.erb
<h1>Vonage Video Demo/ Vonage ビデオデモ</h1>
<picture>
  <source srcset="/img/VonageLogo_Primary_White.png" media="(prefers-color-scheme:dark)">
  <img src="/img/VonageLogo_Primary_Black.png" alt="Vonage logo">
</picture>
<p>This is a demo showing a basic implementation of the <a href="https://developer.vonage.com/en/video/overview" target="_blank">Vonage Video API</a> which creates a new video call and provides the ability to invite another participant by sending them an SMS message containing a link to the video call.</p>
<p>これは、新しいビデオ通話を作成し、ビデオ通話へのリンクを含む SMS メッセージを送信して別の参加者を招待する機能を提供する Vonage Video API の基本的な実装を示すデモです</p>
<%= link_to 'Start the demo/デモを開始する', new_video_call_path, class: 'button' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Demo: Vonage Video</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="//cdn.simplecss.org/simple.min.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <script src="//static.opentok.com/v1/js/video-express.js"></script>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
</html>

app/views/video_calls/_invite.html.erb
<div data-controller="dialog" data-action="click->dialog#backdropClose">
  <dialog data-dialog-target="dialog">
    <%= form_with url: invite_video_call_path(@video_call) do |form| %>
      <%= form.label :participant_name, "Name/名前" %>
      <%= form.text_field :participant_name %>
      <%= form.label :participant_phone_number, "Phone Number/電話番号" %>
      <%= form.text_field :participant_phone_number, placeholder: '818012345678' %>
      <%= form.submit 'Send Invite/招待状を送信する' %>
    <% end %>

    <button type="button" data-action="dialog#close" autofocus>Close/近い</button>
  </dialog>

  <button type="button" data-action="dialog#open">Invite Participant/参加者を招待する</button>
</div>

app/views/video_calls/_join.html.erb
<%= form_with url: join_video_call_path(@video_call) do |form| %>
  <%= form.label :name, "Your Name/あなたのお名前は" %>
  <%= form.text_field :participant_name %>
  <%= form.submit 'Join Video Call/ビデオ通話に参加する' %>
<% end %>

app/views/video_calls/_room.html.erb
<%= render "invite" %>
<%= turbo_frame_tag 'room', data: {
    controller: "join-room",
    join_room_api_key_value: @video_call.application_id,
    join_room_session_id_value: @video_call.session_id,
    join_room_participant_name_value: session[:participant_name],
    join_room_token_value: @token 
  } do %>
  <%= tag.div id: "room-container", data: { action:"turbo:frame-render->join-room#connect" } %>
<% end %>
<%= link_to 'Leave video call/ビデオ通話を終了する', root_path, class: 'button alert' %>

app/views/video_calls/new.html.erb
<h1>Create Video Call/ビデオ通話を作成する</h1>
<p>Start a new video call/新しいビデオ通話を開始する.</p>
<%= form_with model: @video_call do |form| %>
  <%= form.label :name, "Room Name/部屋の名前" %>
  <%= form.text_field :name, required: true %>
  <%= form.submit 'Create Video Call/ビデオ通話を作成する' %>
<% end %>
<% flash.each do |type, message| %>
  <mark class="<%= type %>">
    <%= message %>
  </mark>
<% end %>
</body>

app/views/video_calls/show.html.erb
<h1 class="title"><%= @video_call.name %></h1>
<% if session[:participant_name].present? %>
  <%= render "room" %>
<% else %>
  <%= render "join" %>
<% end %>